name: Lint

on: workflow_call

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: .pre-commit-config.yaml

      - name: Set up for pre-commit
        run: |
          python -m pip install pre-commit
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore pre-commit cache
        uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pre-commit
          key:
            pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files --verbose

      - name: Commit and push changed files
        if: ${{ failure() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Apply automatic fixes"
          git push
